jobs:
- job: Prebuild
  pool:
      vmImage: 'ubuntu-18.04'
  steps:
  - checkout: self
    submodules: recursive

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/examples'
      artifactName: examples
